version: "3.9"
   
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8888:8888
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8888
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTRESQL_DB = postgres
      - POSTRESQL_USER = postgres
      - POSTRESQL_PASSWORD = postgres 
      - POSTGRES_HOST_AUTH_METHOD=trust
    container_name: postgres_db